### PR TITLE
Replace libs folder with dependencies from maven.

### PR DESCRIPTION
**Pull request by lbergelson**
* Remove the checked in libs folder and fetch dependencies from maven central instead.
  This should reduce the growth rate of the git repo when dependencies change and allows easier updating of dependencies.
* One change to a test to remove the use of a method from freemarker which is a deep transitive dependency

@kshakir This is what I was talking about on slack.  Feel free to use it or not. I just have a visceral dislike of checked in dependencies.

### CODE REVIEW

**Comment by alecw** [comment]
Sorry, just noticed that I'm requested to review.  I'm gonna run my integration test.

**Comment by kshakir** [comment]
FYI- I'm also debugging the "other" repo that inherits `Drop-seq`... I'm trying something similar but so far haven't come up with the incantation to get the build to run.

Over in that project I'm trying something like:

```
implementation(project(":dropseq")) {
    attributes{
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_RUNTIME))
    }
}
```

But then getting the very helpful error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':[elided]:compileTestJava'.
> Could not resolve all task dependencies for configuration ':[elided]:testCompileClasspath'.
   > Could not resolve project :dropseq.
     Required by:
         project :[elided]
      > Module '[elided]:dropseq' has been rejected:
           Cannot select module with conflict on capability '[elided]dropseq:unspecified' also provided by [[elided]:dropseq:unspecified(apiElements), [elided]:dropseq:unspecified(runtimeElements)]
   > Could not resolve project :dropseq.
     Required by:
         project :[elided]
      > Module '[elided]:dropseq' has been rejected:
           Cannot select module with conflict on capability '[elided]:dropseq:unspecified' also provided by [[elided]:dropseq:unspecified(apiElements), [elided]:dropseq:unspecified(runtimeElements)]
   > Could not resolve project :dropseq.
     Required by:
         project :[elided] > project :dropseq
      > Module '[elided]:dropseq' has been rejected:
           Cannot select module with conflict on capability '[elided]:dropseq:unspecified' also provided by [[elided]:dropseq:unspecified(apiElements), [elided]:dropseq:unspecified(runtimeElements)]
```

Still looking...

**Comment by alecw** [comment]
I realize we need to make analogous changes to our private java build before we can merge this.  I'm assuming this isn't high priority but I'll try to get to it in the next couple of weeks.

**Comment by kshakir** [comment]
Re the above:

> FAILURE: Build failed with an exception.

Turns out the error occurs when the plugin `id("java-test-fixtures")` has not been added, plus the block: 
```
configurations {
    testFixturesApi {
        extendsFrom(implementation.get())
    }
}
```

When those changes are also added to the downstream project the dependency resolution works. TBH I'm not quite sure what the error means, nor am I clear on how the plugin relates to the error, but again it works. 🤷

**Comment by alecw** [comment]
@kshakir integration test looks fine

**Pull request merged**
